
- name: Register Gitlab job allocation
  shell: "{% raw %}nomad job allocs -t '{{ range . }}{{println .ID}}{{ end }}' gitlab | tr -d '\n' | cut -d '-' -f 1{% endraw %}" 
  environment:
    NOMAD_ADDR: http://nomad.service.consul:4646
  register: gitlab_allocation
  run_once: true

- name: Set Gitlab root password
  shell: "nomad alloc exec {{ gitlab_allocation.stdout }} gitlab-rails runner \"user = User.find_by_username('root'); user.password = '{{ nomad_gitlab_docker_configuration.initial_root_password }}'; user.password_confirmation = '{{ nomad_gitlab_docker_configuration.initial_root_password }}'; user.save!\""
  environment:
    NOMAD_ADDR: http://nomad.service.consul:4646
  run_once: true

- name: Run set Gitlab root API token command
  shell: "nomad alloc exec {{ gitlab_allocation.stdout }} gitlab-rails runner \"token = User.find_by_username('root').personal_access_tokens.create(scopes: [:api, :sudo], name: 'Ansible Setup Token'); token.set_token('{{ nomad_gitlab_root_api_key }}'); token.save\""
  environment:
    NOMAD_ADDR: http://nomad.service.consul:4646
  run_once: true
  register: set_gitlab_api

- name: Set gitlab api token
  ansible.builtin.set_fact:
    gitlab_api_token: "{{ set_gitlab_api.stdout }}"
