---

- name: Create Gitlab Groups
  community.general.gitlab_group:
    server_url: "https://gitlab.{{ zone }}"
    api_token: "{{ gitlab_api_token }}"
    validate_certs: false
    name: "{{ async_item.name }}"
    state: present
  loop: "{{ groups }}"
  loop_control:
    loop_var: "async_item"
  async: 360
  poll: 0
  register: create_gitlab_groups

- name: Check status of each group creation 
  ansible.builtin.async_status:
    jid: "{{ async_item.ansible_job_id }}"
  register: create_gitlab_group_status
  retries: 3O
  delay: 3 
  until: create_gitlab_group_status.finished
  loop: "{{ create_gitlab_groups.results }}"
  loop_control:
    loop_var: "async_item"


