---

- name: Create Gitlab Users
  community.general.gitlab_user:
    server_url: "https://gitlab.{{ zone }}"
    api_token: "{{ gitlab_api_token }}"
    validate_certs: false
    name: "{{ async_item[0].name }}"
    username: "{{ async_item[0].name }}"

- name:

- name: 
  local_action:
