---

- block:
    - ansible.builtin.include_tasks: "setup.yml"
      when: "gitlab_enabled | bool"
    - ansible.builtin.include_tasks: "auth_setup.yml"
      when: "gitlab_enabled | bool"
    - name: Create Gitlab Groups
      vars:
        groups: "{{ item }}"
      include: create_groups.yml
      loop: "{{ nomad_gitlab_groups | list }}"
    - name: Create Gitlab Users
      vars:
        users: "{{ item }}"
      include: create_users.yml 
      loop: "{{ nomad_gitlab_groups | subelements('members') }}"

  tags:
    - gitlab
