- name: Deploy Gitlab job
  ansible.builtin.include_tasks: "setup.yml"
  run_once: true

- name: Create API creds
  ansible.builtin.include_tasks: "api_creds.yml"
  run_once: true

- name: Create OAuth applications in Gitlab
  ansible.builtin.include_tasks: "create_oauth_apps.yml"
  loop: "{{ nomad_gitlab_oauth_applications }}"
  when: nomad_gitlab_oauth_applications is defined
  run_once: true
