---
nomad_version: 1.2.2
nomad_etc_dir: /etc/nomad.d
nomad_data_dir: /opt/nomad
nomad_datacenter: sejoplex
nomad_namespaces:
  - admin
  - client

nomad_csi_plugin_id: azuredisk-csi
nomad_csi_plugin_job_name: "plugin-{{ item }}"
nomad_csi_plugin_image: "mcr.microsoft.com/k8s/csi/azuredisk-csi"
nomad_csi_plugin_image_tag: "v1.24.0"
