---
vm_name: cl2
vm_size: Standard_E2as_v4
admin_username: sejo
vm_image:
  offer: 0001-com-ubuntu-server-focal
  publisher: Canonical
  sku: 20_04-lts
  version: latest
vm_subnet_name: jochen-subnet-vm
vm_ip: 10.42.0.12
