---
nomad_job_traefik:
  certificate_email: #example jmaes@kangaroot.net
  acme_challenge: dns
  volumes:
    - dir: /data/traefik
      container_dir: /config
  service_ports:
    - 8081
    - 80
    - 443
