
nomad_mattermost_job_name: mattermost

nomad_mattermost_group_count: 1

nomad_mattermost_volume_container_mount_point: "/srv/mattermost"


# Mattermost Application Container image
nomad_mattermost_app_docker_image_version: "team"
nomad_mattermost_app_docker_image_name: "mattermost-{{ nomad_mattermost_app_docker_image_version }}-edition"
nomad_mattermost_app_docker_image_tag: "7.1"
nomad_mattermost_app_docker_image: "mattermost/{{ nomad_mattermost_app_docker_image_name }}:{{ nomad_mattermost_app_docker_image_tag }}"


nomad_mattermost_app_pre_task_docker_image: "busybox:{{ nomad_mattermost_app_pre_task_docker_image_tag }}"
nomad_mattermost_app_pre_task_docker_image_tag: "1.33.0"

  # Mattermost Database Container Image
nomad_mattermost_db_docker_image_tag: "13-alpine"
nomad_mattermost_db_docker_image: "postgres:{{ nomad_mattermost_db_docker_image_tag }}"


nomad_mattermost_externalurl: "https://mattermost.{{ zone }}"
nomad_mattermost_database_connection_string: "postgres://{{ nomad_mattermost_database_user }}:{{ nomad_mattermost_database_password }}@localhost:5432/{{ nomad_mattermost_database_name }}?sslmode=disable&connect_timeout=10"
nomad_mattermost_database_user: "mmuser"
# Set this in your inventory
nomad_mattermost_database_password: "{{ nomad_mattermost_db_password }}"
nomad_mattermost_database_type: "postgres"
nomad_mattermost_database_name: "mattermost"


nomad_mattermost_network:
  - name: http
    hostnetwork: public

nomad_mattermost_services:
  - name: mattermost
    port: "{{ nomad_mattermost_network[0].name }}"

nomad_mattermost_volume_mounts:
  - name: "mattermost-data"
    mountpoint: "/mattermost/data"
  - name: "mattermost-db"
    mountpoint: "/var/lib/postgresql/data"
    
nomad_mattermost_app_resources:
  cpu: 2000
  memory: 4000

